### ISSUE TITLE
Optional Portable Crafting Table Recipe

### ISSUE THREAD

**Issue by bb010g** [blay09/CraftCraft#25]
It would be nice if you could disable the portable crafting table recipe in a config file rather than having to put in CraftTweaker recipes.

**Comment by TDarkShadow** [comment]
I agree, or change the recipe from a 1:1 ratio to a one where it requires iron?
Then you could also switch the item icon between them.

**Comment by BlayTheNinth** [comment]
I think CraftTweaker is the way to go for things like this for now, especially considering the way recipes are moving in 1.12+. 

There will probably be a way to modify recipes in Vanilla in 1.13, so I don't think there's much point adding it now, especially since currently in 1.12 locking recipes behind config options is a pain.

(I do realize this post is like nine months old by now)

**Comment by TDarkShadow** [comment]
That is a fair understanding.
